# Generated by Django 6.0.2 on 2026-05-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("sadness", models.IntegerField(default=0)),
                ("action", models.IntegerField(default=0)),
                ("humor", models.IntegerField(default=0)),
                ("thrill", models.IntegerField(default=0)),
            ],
        ),
    ]
