# Generated by Django 6.0.2 on 2026-05-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="humor",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="sadness",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="thrill",
        ),
        migrations.AddField(
            model_name="movie",
            name="happy",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="weird",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="action",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
